openapi: 3.0.0
info:
  title: Authentication API
  description: API for user authentication in the RAG Chatbot system
  version: 1.0.0
servers:
  - url: http://localhost:8000/api/v1
    description: Development server
paths:
  /auth/signup:
    post:
      summary: User registration
      description: Creates a new user account with background information
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - email
                - password
                - software_background
                - hardware_background
              properties:
                name:
                  type: string
                  example: "John Doe"
                email:
                  type: string
                  format: email
                  example: "john.doe@example.com"
                password:
                  type: string
                  format: password
                  example: "securePassword123"
                software_background:
                  type: string
                  enum: [beginner, intermediate, advanced]
                  example: "intermediate"
                hardware_background:
                  type: string
                  enum: [none, basic, advanced]
                  example: "basic"
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "User created successfully"
                  user_id:
                    type: string
                    example: "123e4567-e89b-12d3-a456-426614174000"
        '400':
          description: Invalid input
        '409':
          description: Email already exists
  /auth/signin:
    post:
      summary: User login
      description: Authenticates a user and returns a JWT token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: "john.doe@example.com"
                password:
                  type: string
                  format: password
                  example: "securePassword123"
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                  token_type:
                    type: string
                    example: "bearer"
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                        example: "123e4567-e89b-12d3-a456-426614174000"
                      name:
                        type: string
                        example: "John Doe"
                      email:
                        type: string
                        format: email
                        example: "john.doe@example.com"
        '401':
          description: Invalid credentials
  /auth/signout:
    post:
      summary: User logout
      description: Invalidates the user's session (client-side token removal is primary)
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Logout successful
  /auth/me:
    get:
      summary: Get current user
      description: Returns information about the currently authenticated user
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Current user information
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: "123e4567-e89b-12d3-a456-426614174000"
                  name:
                    type: string
                    example: "John Doe"
                  email:
                    type: string
                    format: email
                    example: "john.doe@example.com"
                  software_background:
                    type: string
                    enum: [beginner, intermediate, advanced]
                    example: "intermediate"
                  hardware_background:
                    type: string
                    enum: [none, basic, advanced]
                    example: "basic"
        '401':
          description: Unauthorized
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT