openapi: 3.0.0
info:
  title: Content Personalization API
  description: API for personalizing textbook content based on user background
  version: 1.0.0
servers:
  - url: http://localhost:8000/api/v1
    description: Development server
paths:
  /personalize:
    post:
      summary: Personalize chapter content
      description: Adjusts chapter content based on the user's background level
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - chapter_id
                - chapter_content
              properties:
                chapter_id:
                  type: string
                  description: Unique identifier for the chapter
                  example: "week-03-hardware-platforms"
                chapter_content:
                  type: string
                  description: Original chapter content to be personalized
                  example: "Hardware platforms for robotics include..."
                background_level:
                  type: string
                  enum: [beginner, intermediate, advanced]
                  description: Override user's background level (optional, defaults to user's level)
                  example: "beginner"
      responses:
        '200':
          description: Personalized content
          content:
            application/json:
              schema:
                type: object
                properties:
                  personalized_content:
                    type: string
                    example: "Hardware platforms for robotics include (with additional explanations for beginners)..."
                  original_background:
                    type: string
                    enum: [beginner, intermediate, advanced]
                    example: "beginner"
                  processing_time:
                    type: number
                    example: 1.23
        '400':
          description: Invalid input
        '401':
          description: Unauthorized - authentication required
        '500':
          description: Internal server error
      security:
        - BearerAuth: []
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT